# Accepts vars:
# - copy_to_become_password: true to automatically set `become_password`
#   as well (if not yet defined).
---
- name: SET_FACT | init
  ansible.builtin.set_fact:
    password_prompt:
  tags: always

- name: Prompt for ssh password if necessary
  when: ansible_password is undefined
  block:
    - name: PAUSE | Conditionally prompt for ssh password
      ansible.builtin.pause:
        prompt: "Password for {{ ansible_user | d('') }}@{{ ansible_host | d('unknown') }}"
        echo: false
      register: password_prompt
      no_log: true

    - name: SET_FACT | Set ansible_password
      ansible.builtin.set_fact:
        ansible_password: "{{ password_prompt.user_input }}"
      no_log: true

- name: SET_FACT | Set ansible_become_password to be the same as ssh password
  ansible.builtin.set_fact:
    ansible_become_password: "{{ ansible_password }}"
  no_log: true
  when: copy_to_become_password | d(false) and ansible_become_password is undefined

- name: COMMAND | Test the password for fail-fast
  ansible.builtin.command: '/usr/bin/true'
  changed_when: false
  become: true
  when: password_prompt.user_input is defined
