---
name: Ansible Molecule

on:
  push:
    branches:
        - master
  pull_request:
  schedule:
    - cron: "10 10 * * SUN"
  workflow_dispatch:

env:
  # https://www.jeffgeerling.com/blog/2020/getting-colorized-output-molecule-and-ansible-on-github-actions-ci
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  check-needs-run:
    runs-on: ubuntu-latest
    outputs:
      needs_run: ${{ steps.check-event.outputs.changed_all == 'true' || steps.changes.outputs.ansible == 'true' }}
    steps:
      # NOTE: code needs to be checked out to even get at .github/paths-filter.yml
      - uses: actions/checkout@v3

      # TODO: is there an easier way to do this?
      - name: Determine if we apply to all files
        id: check-event
        if: contains(fromJSON('["schedule", "workflow_dispatch"]'), github.event_name)
        run: echo "changed_all=true" >> "$GITHUB_OUTPUT"

      - name: Check for changes in relevant files
        id: changes
        if: steps.check-event.outputs.changed_all != 'true'
        uses: dorny/paths-filter@v2
        with:
          filters: .github/paths-filter.yml

  ansible-molecule:
    needs: check-needs-run
    if: needs.check-needs-run.outputs.needs_run

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          #- geerlingguy/docker-centos7-ansible:latest
          #- geerlingguy/docker-rockylinux8-ansible:latest
          #- geerlingguy/docker-rockylinux9-ansible:latest
          #- ghcr.io/artis3n/docker-almalinux8-ansible:latest
          #- ghcr.io/artis3n/docker-rhel8-ansible:latest
          #- ghcr.io/artis3n/docker-oraclelinux8-ansible:latest
          #- ghcr.io/artis3n/docker-amazonlinux2-ansible:latest
          - ghcr.io/artis3n/docker-ubuntu2204-ansible:latest
          #- geerlingguy/docker-ubuntu2004-ansible:latest
          #- geerlingguy/docker-ubuntu1804-ansible:latest
          #- geerlingguy/docker-ubuntu1604-ansible:latest
          #- ghcr.io/artis3n/docker-debian12-ansible:latest
          #- geerlingguy/docker-debian11-ansible:latest
          #- geerlingguy/docker-debian10-ansible:latest
          #- geerlingguy/docker-debian9-ansible:latest
          #- geerlingguy/docker-fedora31-ansible:latest
          #- ghcr.io/artis3n/docker-arch-ansible:latest
          #- ghcr.io/artis3n/docker-opensuse-tumbleweed-ansible:latest
          #- ghcr.io/artis3n/docker-opensuse-leap-ansible:latest

        role:
          - add_to_config_file

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.x
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'   # avoid warning in logs
          cache: 'poetry'

      - name: Poetry install packages
        run: poetry install --no-interaction

      - name: Run Ansible Molecule
        id: molecule
        env:
          MOL_IMAGE: ${{ matrix.image }}
        run: >
          cd roles/${{ matrix.role }} &&
          poetry run molecule test
