---
# Automated release playbook for Ansible Collections.
#
# Based on:
#   https://github.com/geerlingguy/ansible-collection-mac/blob/9e24c7312d5cae4773e5312fd8f0b65d0ee7a5db/galaxy-deploy.yml
#
# Originally based on Ericsysmin's 2020 blog post. Meant to be used in a GitHub
# Actions CI environment.
#
# Requires a ANSIBLE_GALAXY_API_KEY secret to be configured on the GitHub repo.
#
# Usage:
#   ansible-playbook -i 'localhost,' galaxy-publish.yml -e "github_tag=${{ github.ref }}"

- name: Deploy to Galaxy
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    namespace: huyz
    collection: general
    # Requires github_tag to be set when calling playbook.
    release_tag: "{{ github_tag.split('/')[-1] }}"

  tasks:
    - name: LINEINFILE | Ensure the galaxy.yml tag is up to date.
      ansible.builtin.lineinfile:
        path: galaxy.yml
        regexp: "^version:"
        line: 'version: "{{ release_tag }}"'

    - name: FACT | set build filename
      ansible.builtin.set_fact:
        build_filename: "./{{ namespace }}-{{ collection }}-{{ release_tag }}.tar.gz"

    - name: SHELL | Build the collection.
      ansible.builtin.shell: |
        set -o pipefail
        if [[ -e "{{ build_filename }}" ]]; then
          md5="$(md5sum "{{ build_filename }}" | awk '{print $1}')"
        fi
        if ansible-galaxy collection build -v --force; then
          if [[ -e "{{ build_filename }}" ]]; then
            new_md5="$(md5sum "{{ build_filename }}" | awk '{print $1}')"
            if [[ "$md5" != "$new_md5" ]]; then
              exit 192
            else
              exit 0
            fi
          else
            exit 1
          fi
        fi
        exit $?
      register: _build_result
      changed_when: _build_result.rc == 192

    - name: COMMAND | Publish the collection.
      ansible.builtin.command: >
        ansible-galaxy collection publish -v --api-key '$$ANSIBLE_GALAXY_API_KEY' \
          "{{ build_filename }}"
      changed_when: false
